# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

steps:
- script: echo Hello, Vigneshwar!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: S3Upload@1
  inputs:
    awsCredentials: 'cloudops'
    regionName: 'ap-south-1'
    bucketName: 'demo-usha-devops'
    globExpressions: '*'
    createBucket: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'git config --global http.sslVerify false'


pool:
  name: Default
