trigger:
- main

jobs:
- job: BuildAndDeploy
  pool:
    name: Default
  steps:
  - script: echo Hello, Vigneshwar!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'

  - task: S3Upload@1
    inputs:
      awsCredentials: 'cloudops'
      regionName: 'ap-south-1'
      bucketName: 'demo-usha-devops'
      globExpressions: '*'
      createBucket: true

- job: DisableSSLVerification
  pool:
    name: Default
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'git config --global http.sslVerify false'
